export default [
  {
    team: 'Business Intelligence & Machine Learning',
    postings: [
      {
        additionalPlain: "LA VIE DE MWMER\n\n🎸 Être un acteur de l’industrie de la créativité : Nous sommes une scale-up en pleine croissance, rentables depuis plusieurs années, et nous évoluons dans un marché au potentiel illimité ! Que ce soit pour collaborer avec des DJ comme Martin Solveig et DJ Jazzy Jeff, de travailler en étroite collaboration avec Google et Apple, ou de concevoir de nouveaux jeux dans notre propre studio de jeux mobiles, notre univers est riche et varié !\n\n💫 Incarner une vision : Développer des applications mobiles performantes pour libérer la créativité de nos utilisateurs. Nos valeurs sont notre ADN, et nous avons à coeur que cela se reflète dans nos produits et notre façon de travailler.\n\n💪🏼 Vivre dans une ambiance motivante : Un esprit sain dans un corps sain ! Parce qu’on sait qu’on ne travaille bien que si l’on se sent bien, nous mettons à disposition : une salle de sport dans les locaux, des fruits frais, des snacks, et des boissons mais aussi des espaces détente, jeux, et notre propre studio de musique ! Une fois par mois : services de coiffure, de manucure/pédicure, et d’osthéopathie. Et maintenant que les mesures sanitaires s’assouplissent, nous réorganisons nos premiers afterworks, et des teams building sont à venir ! Où s’est déroulé notre dernier séminaire ? A Ibiza bien sûr 😉\n\n🦄 Sans oublier : Des tickets restaurants (carte Swile), une mutuelle et la possibilité d’une place en crèche, une prime d’intéressement, et un plan d’épargne entreprise. Et bien sûr : de nombreuses perspectives de carrière !\n\nTu nous as lu jusqu’ici et ça te parle ? Tu sais ce qu’il te reste à faire ✅  !\n\n\nLE PROCESSUS DE RECRUTEMENT\n- Un premier appel de 30 minutes avec la Talent Acquisition Manager,\n- Un Test Technique,\n- Un entretien de 1 heures en visio avec la Responsable du Pôle Business Intelligence,\n- Un dernier entretien d'1 heure dans nos bureaux avec le CTO.\n- Bienvenue !\n",
        additional: "<div><b style=\"font-size: 18px\">LA VIE DE MWMER</b></div><div><br></div><div>🎸 Être un acteur de l’industrie de la créativité : Nous sommes une scale-up en pleine croissance, rentables depuis plusieurs années, et nous évoluons dans un marché au potentiel illimité ! Que ce soit pour collaborer avec des DJ comme Martin Solveig et DJ Jazzy Jeff, de travailler en étroite collaboration avec Google et Apple, ou de concevoir de nouveaux jeux dans notre propre studio de jeux mobiles, notre univers est riche et varié !</div><div><br></div><div>💫 Incarner une vision : Développer des applications mobiles performantes pour libérer la créativité de nos utilisateurs. Nos valeurs sont notre ADN, et nous avons à coeur que cela se reflète dans nos produits et notre façon de travailler.</div><div><br></div><div>💪🏼 Vivre dans une ambiance motivante : Un esprit sain dans un corps sain ! Parce qu’on sait qu’on ne travaille bien que si l’on se sent bien, nous mettons à disposition : une salle de sport dans les locaux, des fruits frais, des snacks, et des boissons mais aussi des espaces détente, jeux, et notre propre studio de musique ! Une fois par mois : services de coiffure, de manucure/pédicure, et d’osthéopathie. Et maintenant que les mesures sanitaires s’assouplissent, nous réorganisons nos premiers afterworks, et des teams building sont à venir ! Où s’est déroulé notre dernier séminaire ? A Ibiza bien sûr 😉</div><div><br></div><div>🦄 Sans oublier : Des tickets restaurants (carte Swile), une mutuelle et la possibilité d’une place en crèche, une prime d’intéressement, et un plan d’épargne entreprise. Et bien sûr : de nombreuses perspectives de carrière !</div><div><br></div><div>Tu nous as lu jusqu’ici et ça te parle ? Tu sais ce qu’il te reste à faire ✅&nbsp; !</div><div><br></div><div><br></div><div><b style=\"font-size: 18px\">LE PROCESSUS DE RECRUTEMENT</b></div><div>- Un premier appel de 30 minutes avec la Talent Acquisition Manager,</div><div>- Un Test Technique,</div><div>- Un entretien de 1 heures en visio avec la Responsable du Pôle Business Intelligence,</div><div>- Un dernier entretien d'1 heure dans nos bureaux avec le CTO.</div><div>- Bienvenue !</div>",
        categories: {
          commitment: 'CDI (Full-Time)',
          department: 'Tech Factory 💻',
          location: 'PARIS',
          team: 'Business Intelligence & Machine Learning',
        },
        createdAt: 1597160563288,
        descriptionPlain: 'QUI SOMMES NOUS ?\n\nFondée en 2012, MWM fait aujourd’hui partie des start-ups françaises les plus prometteuses de l’écosystème French Tech, et nous sommes fières et fiers de faire partie du programme FT120 pour 2021 et de porter les couleurs de la France à l’international ! 🇫🇷\n\nNous sommes une tech factory, 1er éditeur mondial d’apps de musique et leader dans les apps de créativité. Nos trois valeurs fondatrices sont la Passion, l’Impact, et la Résilience. En 2020 nous avons réalisé une levée de fonds de 50 millions d’euros et créé notre propre studio de jeux mobiles. 💪🏼 \n\nNous sommes 130 MWMers en quête permanente d’innovation et d’indépendance technique, et nous travaillons ensemble vers un seul but : faire des applications mobiles inspirantes et ambitieuses.💡\n\nNos produits ? Plus de 30 apps dans la musique, et plus généralement dans la créativité : la photo, la vidéo, le dessin… Nos apps sont utilisées par des millions d’utilisateurs à travers le monde, et comptent plus de 450 millions de téléchargements.\n\nAlors, intéressé.e ? La suite par ici !\n',
        description: '<div><b style="font-size: 18px">QUI SOMMES NOUS ?</b></div><div><br></div><div>Fondée en 2012, MWM fait aujourd’hui partie des <b>start-ups françaises les plus prometteuses de l’écosystème French Tech</b>, et nous sommes fières et fiers de faire partie du programme FT120 pour 2021 et de porter les couleurs de la France à l’international ! 🇫🇷</div><div><br></div><div>Nous sommes une <b>tech factory, 1er éditeur mondial d’apps de musique et leader dans les apps de créativité</b>. Nos trois valeurs fondatrices sont la <b>Passion</b>, <b>l’Impact</b>, et la <b>Résilience</b>. En 2020 nous avons réalisé une <b>levée de fonds de 50 millions d’euros</b> et créé <b>notre propre studio de jeux mobiles</b>. 💪🏼&nbsp;</div><div><br></div><div>Nous sommes <b>130 MWMers</b> en quête permanente d’innovation et d’indépendance technique, et nous travaillons ensemble vers un seul but : <b>faire des applications mobiles inspirantes et ambitieuses</b>.💡</div><div><br></div><div>Nos produits ? <b>Plus de 30 apps dans la musique, et plus généralement dans la créativité : la photo, la vidéo, le dessin</b>… Nos apps sont utilisées par des millions d’utilisateurs à travers le monde, et comptent <b>plus de 450 millions de téléchargements</b>.</div><div><br></div><div>Alors, intéressé.e ? La suite par ici !</div>',
        id: 'f95a3437-70e7-4872-b03d-574f53451c09',
        lists: [
          {
            text: 'Mission & challenges 💪',
            content: "<li>En plus de son équipe de Machine Learning, qui intègre des innovations de Core ML dans ses applications de créativité, MWM a son propre <b>pôle de Business Intelligence</b>. En effet en rejoignant le pôle Business Intelligence composé de plusieurs Data Scientists, tu auras notamment pour responsabilité de <b>construire des modèles permettant d’améliorer les performances de nos applications</b> (rétention, engagement, LTV...), ainsi que d'aider les équipes métier à prendre les meilleures décisions possibles via des <b>algorithmes de Data Science orientés Marketing &amp; Business</b>.</li><div><br></div><li>Exploiter des quantités massives de données provenant de différentes sources (user data, app data…),</li><li>Proposer et déployer des use cases innovants et variés, allant du marketing prédictif au NLP en passant par des moteurs de recommandations, en accord avec la roadmap stratégique,</li><li>Challenger les modèles de Machine Learning déjà existants qui aident l’ensemble des équipes dans la prise de décisions : intégration de nouvelles données, optimisation des modèles en termes d’amélioration de temps de calcul et de robustesse, implémentation sur systèmes embarqués…,</li><li>Relever avec toutes les équipes MWM les défis créatifs de demain.</li>",
          },
          {
            text: 'Être Data Scientist chez MWM',
            content: '<li>La data occupe une place centrale chez MWM ! Si le compromis biais-variance t’empêche régulièrement de dormir mais que des millions de données ne t’effraient absolument pas, notre équipe Business Intelligence, composée aujourd’hui de 3 personnes, est faite pour toi.</li><li>Au-delà de notre ambiance de travail décontractée, nous sommes très soucieux de garantir la rigueur scientifique et la qualité de tout ce qui passe en production.</li>',
          },
          {
            text: '🧐 A propos de toi',
            content: "<li>Diplômé.e d’une grande école d’ingénieurs ou de l’université (Bac +5) avec une spécialisation en data science,</li><li><b>Au moins 2 ans d’expérience</b> sur un poste similaire dans l’univers du digital et vous maitrisez la conception, l’optimisation et la mise en production des algorithmes de Machine Learning pour stimuler l’innovation produit,</li><li>Bonnes connaissances dans les librairies de data science (Scikit-Learn, Pandas, NumPy, SciPy) et dans au moins un framework (Keras, PyTorch,...). Tu es doté.e d’un fort esprit analytique et d’une excellente compréhension des enjeux et des leviers du marketing digital,</li><li>Tu as l’esprit d'équipe : tu souhaites rejoindre une petite équipe et collaborer directement avec des collègues travaillant sur le développement mobile et back-end, les produits et le marketing, pour construire ensemble les produits MWM,</li><li>Tu es <a href=\"http://proactif.ive\" class=\"postings-link\">proactif.ive</a>, tu n'hésites pas à proposer des axes d’amélioration sur les processus existants.</li><div><br></div><div><i>Encore mieux si tu :</i></div><li>as déjà utilisé Google Cloud Platform</li><li>possèdes une appétence pour l’encadrement de profils plus juniors.</li><li>as une première expérience dans un environnement start-up.</li>",
          },
        ],
        text: 'Data Scientist',
        hostedUrl: 'https://jobs.lever.co/musicworldmedia/f95a3437-70e7-4872-b03d-574f53451c09',
        applyUrl: 'https://jobs.lever.co/musicworldmedia/f95a3437-70e7-4872-b03d-574f53451c09/apply',
      },
    ],
  },
];
